### ISSUE TITLE
BUG!BUG!BUG!

### ISSUE THREAD

**Issue by pengweiqhca** [Meowtrix/MoeIDE#1]
如果C:\Users{username}\AppData\Roaming\Meowtrix\MoeIDE\userconfig.xml不存在....
System.TypeInitializationException: Meowtrix.MoeIDE.SettingsManager
System.IO.FileSystemWatcher..ctor(String path, String filter)

**Comment by huoyaoyuan** [comment]
啊，以前没用过FileSystemWatcher，不知道在文件不存在的情况下还会失败的
已在代码中修复，将会于下一个版本中更新
