### ISSUE TITLE
Color of Fonts

### ISSUE THREAD

**Issue by ohlawdie** [Meowtrix/MoeIDE#17]
Hey Meowtrix, I think everything is working fine - cool extension! I am just wondering, is there any way to change the theme of the editor without changing the color of the font? Is there any extension out there that would handle such a thing?

Thanks!

**Comment by huoyaoyuan** [comment]
The themes are edited manually by me based on the default Visual Studio themes, using official [Color Theme Editor](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2019ColorThemeEditor). What I really did was exploring how to ship a theme with vsix.
According to the [blog post](https://devblogs.microsoft.com/visualstudio/theming-in-visual-studio-just-got-a-lot-easier/) about official theming, creating a transparent theme may be easier that just set the base colors with transparency.

**Comment by ohlawdie** [comment]
Thanks! 👍

**Comment by huoyaoyuan** [comment]
Well I've tried the new color theme designer, but it doesn't support transparency in base colors. So there's still a lot of work to edit the color table manually.
