### ISSUE TITLE
Transparency does not work on VS 2019 (Version 16.2.2)

### ISSUE THREAD

**Issue by henry9836** [Meowtrix/MoeIDE#18]
Transparency doesn't work in the latest visual studio. Visual studio is also complaining that MoeIDE is using a deprecated API and it refered me here: https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019

![screenshot](https://i.imgur.com/pjcOv4k.png)

**Comment by huoyaoyuan** [comment]
The latest PR should have fixed this problem, but it's not published to VS gallery yet.

**Comment by henry9836** [comment]
guess i'll wait then

**Comment by henry9836** [comment]
Updated to latest version of MoeIDE manually and now it works

![pictureofitworking](https://i.imgur.com/xX15LCt.png)
