### ISSUE TITLE
一个关于代码提示框的透明度的小问题（vs2019）

### ISSUE THREAD

**Issue by Maple512** [Meowtrix/MoeIDE#20]
![{WTE{Y90LD7SR7T$A73R088](https://user-images.githubusercontent.com/34236341/64430578-23525100-d0eb-11e9-9a66-fc64c72f18ba.png)
非常喜欢这个插件！请问这里的透明度在哪里改呢？谢谢

**Comment by huoyaoyuan** [comment]
透明度完全来自于VS的颜色字典，只有背景图片属于程序部分
可以考虑给VS挂上调试器，然后在Live Visual Tree里寻找相应的key，或者自己在字典里根据名称猜

**Comment by Maple512** [comment]
好的，谢谢
