### ISSUE TITLE
VS2019 ASP.NET Forms editor crashs When MoeIDE is using

### ISSUE THREAD

**Issue by vifimx** [Meowtrix/MoeIDE#21]
When I create a asp.net project and open an .aspx file , VS2019 will break without any warning.
And I noticed that aspx was opened by (default) Forms editor. 
![image](https://user-images.githubusercontent.com/43158651/64599124-70843a80-d3eb-11e9-9799-f77e6ddcac69.png)

**Comment by huoyaoyuan** [comment]
If a component is WinForm(which doesn't support transparency), and uses a transparent color in the theme, it will crash. An example is `.ruleset` editor.
You can switch to default theme to confirm this.
I don't have any idea to solve this yet.

**Comment by vifimx** [comment]
Furthermore，it seems that other themes(not transparent) won't help if the extension is still running . I hope this will be of some help.

**Comment by vifimx** [comment]
I've disabled the visual assisst plug-in, and replaced it with resharper, the aps.net project works fine now, but it's still slow to load. Anyway,this problem seems solved by changing other plugine.
