### ISSUE TITLE
vs2015, An error occurred while loading this property page

### ISSUE THREAD

**Issue by Out3ider** [Meowtrix/MoeIDE#3]
as title
![image](https://cloud.githubusercontent.com/assets/19818953/18673543/bc718a70-7f7e-11e6-980f-98c852f07f9e.png)
I appreciate your elegant plug-in.But it doesn't work

**Comment by huoyaoyuan** [comment]
It seems like a dependency dll can't be loaded correctly.
Maybe you can check the files installed first: (extension folder is random)
![image](https://cloud.githubusercontent.com/assets/5644458/18675895/67a95c22-7f86-11e6-8b9d-f342fe7d67cb.png)
I can infer what happens, but cannot reproduce, even if I install it from VSGallery.

**Comment by deKross** [comment]
I have same issue. And I have same list of files as on screenshot.

**Comment by huoyaoyuan** [comment]
Trying to figure out the reason. Maybe related to system/VS language setting.

**Comment by huoyaoyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/5644458/19668217/b5cb5cee-9a88-11e6-80b0-2b69e9a50569.png)
Name of the resource file is mismatched.

**Comment by huoyaoyuan** [comment]
@Out3ider @deKross try 1.3.3 please.
