### ISSUE TITLE
Support visual studio 2017

### ISSUE THREAD

**Issue by pengweiqhca** [Meowtrix/MoeIDE#4]

**Comment by huoyaoyuan** [comment]
Planned.
Not sure if theme key changed in VS2017.

**Comment by MikiraSora** [comment]
Now VisualStudio 2017 is came out, If you really want to support to this version.Please modified Install Target in file "source.extension.vsixmanifest".Like this:
![image](https://cloud.githubusercontent.com/assets/7549173/23703301/3345ebd8-043a-11e7-9c15-341f542dea83.png)
And then build them.If there was occured error.Nerver mind.You can found new vsix file and open it.
ENJOY!

![image](http://p1.bqimg.com/1949/598963ddfcc62395.png)

**Comment by huoyaoyuan** [comment]
Simply changing the manifest does make it work, but there are two things I'm looking about:
  - VS2017 makes some changes to vsix format, considering to stop further updates of VS2015 or not.
  - VS2017 Color Theme Editor has not been released, but the themes files for VS2015 seems to have some bugs.

**Comment by MikiraSora** [comment]
yeah,So this is a matter of expediency and I'm still waiting for your new version :D .

**Comment by huoyaoyuan** [comment]
Triy to update SDK version to 2017, and build successfully.
Now I need some one to test if the version built by 2017 SDK can work with 2015. I've uninstalled 2015 and it's SDK 😛 
[test.zip](https://github.com/Meowtrix/MoeIDE/files/838968/test.zip)

**Comment by MikiraSora** [comment]
无论是你给的test还是我改的，只要是右键"查找所有引用"然后选一个跳转就会Crash.
但禁用插件回去就没问题了.还有Debug断点的时候，跳转到一些类(找不到规律)也会Crash。

**Comment by huoyaoyuan** [comment]
ActivityLog.xml有没有（拖到结尾找Exception），或者你直接使用调试器挂在实验实例上查看一下Exception？
注意我说的场合是**新编译的**（使用17SDK）**在15上**的工作情况，在17上的工作情况我可以自己Debug。

**Comment by MikiraSora** [comment]
抱歉我忘记说我是2017 Community(绝望

**Comment by huoyaoyuan** [comment]
Support added at v1.3.4.
