### ISSUE TITLE
Dark Theme and punctuation.

### ISSUE THREAD

**Issue by frederikstonge** [Meowtrix/MoeIDE#5]
When using the dark theme, i find it hard to see these symbols :

"!"
"="
"=="
"."
"=>"

Font is black and i'm using 2017 so i cannot edit it, could you find a color that is easier to see for the dark theme please? :)

Thanks a lot, love that extension!

**Comment by huoyaoyuan** [comment]
This is a known issue, but I've not figured out what's wrong in the dark theme file.
[Color Theme Editor](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2015ColorThemeEditor) for VS2017 is still not released, so it's difficult to do further fix (because I've uninstalled 2015).
I'd like someone to remind the VS team about this. ☹️

**Comment by huoyaoyuan** [comment]
Further more: I've considered to generate theme file dynamically, instead of distributing pre-edited theme file. But this may need a lot of work.

**Comment by frederikstonge** [comment]
It's weird because the real dark theme of visual studio doesn't have this issue. I thought it was something done on your side! Thanks for your input!!

**Comment by Code-ScottLe** [comment]
FYI, you can temporary fix this by go to Options => Environment => Fonts and Colors => Display Items => Operators and manually flip the Item Foreground to White.

**Comment by Thouce** [comment]
theme key:"文本编辑器→运算符-前景色"，改为明亮的颜色即可。

**Comment by zahasoftware** [comment]
Current cursor is black, Operator can be fix with Code-ScottLe answer, but current the square of current cursor is black...

**Comment by vncastanheira** [comment]
There is a [Color Theme Editor for VS2017 ](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2017ColorThemeEditor)now, maybe it can help.

**Comment by Scrxtchy** [comment]
Hmm, smells like the theme was copied over from the light one. You can see that the startpage also has a light background. In comparison to VS's dark theme, this is meant to be dark too

and the icons in the UI

**Comment by Scrxtchy** [comment]
Was able to _Fix_ the icons by fucking with the environment registry. But this also means breaking transparency altogether, otherwise the startpage fix is https://github.com/Scrxtchy/MoeIDE/commit/699ff0fc362d132107ac2ac50edc822861dfe236

**Comment by Scrxtchy** [comment]
And with an additional countless hacking, and the tool provided by _vncastanheira_
![image](https://user-images.githubusercontent.com/12771982/47589709-ac6e0700-d9b5-11e8-80ac-a2bf7dacd477.png)

These control the glyphs on the toolbar. Having these at 00 for transparency flicks them white, 01 is enough to not cause that and not be noticable enough to be a problem
![image](https://user-images.githubusercontent.com/12771982/47589756-d6272e00-d9b5-11e8-8d24-69875971ba83.png)

**Comment by Synthetikaryote** [comment]
I use the Color Theme Editor for VS2017 to fix this issue on my end.  Here's what I found:
![image](https://user-images.githubusercontent.com/1689553/56698206-02421400-66a6-11e9-944d-b765209074a5.png)
