### ISSUE TITLE
VS2017 Crash - Find All References Window

### ISSUE THREAD

**Issue by Bluespide** [Meowtrix/MoeIDE#6]
C# -> Right click on any class -> Find All References -> The mouse hover over a class in the reference window would normally pop up a tiny preview windows, but VS2017 crashes for me at this point with this extension.

**Comment by huoyaoyuan** [comment]
Should be fixed in v1.3.6.
This was reported by @MikiraSora, but the fix haven't been pushed yet.
You can check if the new version works.

**Comment by Bluespide** [comment]
Wow that was a fast fix, thanks!
